project:
  type: website
lang: es   

website:
  title: "La Renovable"
  sidebar:
    contents:
      - about.qmd
      # - text: "Número 1"
      #   href: numero-001.qmd
      # - text: "Número 4"
      #   href: numero-004.qmd

format:
  html:
    theme: cosmo
    css: styles.css
